apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-virtual-agent.fullname" . }}
  labels:
    {{- include "ai-virtual-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: proxy
      port: 8888
      protocol: TCP
      targetPort: oauth-proxy
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ai-virtual-agent.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
